import AuthProvider from "./AuthProvider";
import NavMenu from "./NavMenu";
import "./globals.css";

export const metaData = {
  title: "Create Next App",
  description: "Generated by Create Next App",
};
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="en">
        <body>
          <NavMenu />
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}
